[general]
import = [
  "~/.config/alacritty/themes/themes/monokai.toml"
]

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[window]
opacity = 0.75

[terminal.shell]
program = "/bin/bash"
args = [ "--login" ] # need this for RVM, not sure what it does
